import { BadgeCheck, Building2, Mail, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { PageHeader } from "../../../components/ui/PageHeader";
import { useAuth } from "../../auth/auth";

export function ProfilesPage() {
  const { user } = useAuth();
  if (!user) return null;
  const actorNumber = user.studentId ? "Student profile" : user.teacherId ? "Teacher profile" : user.driverId ? "Driver profile" : user.examinerId ? "Examiner profile" : user.employeeId ? "Employee profile" : "Platform account";
  return <div className="page-stack"><PageHeader title="My profile" subtitle="Your authenticated SmartSchool account and organizational context"/><section className="profile-hero"><span className="profile-avatar-xl">{user.initials}</span><div><span className="eyebrow">{actorNumber}</span><h2>{user.name}</h2><p><Mail size={15}/>{user.email}</p><div className="profile-badges"><span><ShieldCheck size={14}/>{user.role}</span>{user.impersonated && <span><BadgeCheck size={14}/>Support session</span>}</div></div></section><section className="profile-info-grid"><article><span className="profile-info-icon"><UserRound/></span><div><small>Account type</small><b>{user.accountType || "SmartSchool user"}</b><p>Your access is controlled by assigned roles and permissions.</p></div></article><article><span className="profile-info-icon"><Building2/></span><div><small>School context</small><b>{user.school || "Assigned school"}</b><p>{user.schoolId ? "School assigned to this account" : "Platform-level account"}</p></div></article><article><span className="profile-info-icon"><MapPin/></span><div><small>Branch context</small><b>{user.branchId ? "Assigned branch" : "All authorized branches"}</b><p>Branch scope is taken securely from your access token.</p></div></article><article><span className="profile-info-icon"><ShieldCheck/></span><div><small>Access roles</small><b>{user.roles.join(", ") || user.role}</b><p>Identity and business context are managed by SmartSchool.</p></div></article></section><section className="surface profile-security-note"><div><h3>Security & identity</h3><p>Internal database identifiers are intentionally hidden. Tenant, school, branch and actor scope are resolved from your authenticated session and are not editable here.</p></div></section></div>;
}
