import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, ClipboardCheck, Gauge, Plus, RefreshCw, Users } from "lucide-react";
import { api } from "../../../core/api/api";
import { getErrorMessage } from "../../../core/api/errorMessage";
import { PageHeader } from "../../../components/ui/PageHeader";
import { Modal, useUi } from "../../../components/ui/InteractiveUi";
import { HrPage } from "../../hr/pages/HrPage";
import { useAuth } from "../../auth/auth";

type Row=Record<string,any>;
const unwrap=(d:any):Row[]=>Array.isArray(d)?d:Array.isArray(d?.items)?d.items:Array.isArray(d?.value)?d.value:[];
const val=(o:Row,k:string)=>o[k]??o[k[0].toUpperCase()+k.slice(1)]??"—";

function TeacherWorkspace(){
 const {user}=useAuth(); const {notify,beginBusy}=useUi();
 const [me,setMe]=useState<Row|null>(null),[dash,setDash]=useState<Row>({}),[classes,setClasses]=useState<Row[]>([]),[students,setStudents]=useState<Row[]>([]),[timetable,setTimetable]=useState<Row[]>([]),[assignments,setAssignments]=useState<Row[]>([]),[workload,setWorkload]=useState<Row>({});
 const [tab,setTab]=useState("overview"),[assignmentOpen,setAssignmentOpen]=useState(false),[leaveOpen,setLeaveOpen]=useState(false);
 const [assignment,setAssignment]=useState<Row>({Type:"HOMEWORK",Title:"",Description:"",Instructions:"",DueAt:"",TotalMarks:100,AllowLateSubmission:false,MaxAttempts:1,CourseOfferingId:"",ClassSectionId:""});
 const [leave,setLeave]=useState<Row>({FromDate:"",ToDate:"",LeaveType:"CASUAL",Reason:""});
 const tenant=sessionStorage.getItem("selected_tenant_id")||localStorage.getItem("tenant_id")||user?.tenantId||"";
 async function load(){const end=beginBusy("Loading teacher workspace…");try{const m=(await api.get("/api/teachers/me")).data;setMe(m);const id=m.employeeId??m.EmployeeId;if(!id)return;const p={params:{tenantId:tenant}};const [d,c,s,t,a,w]=await Promise.all([api.get(`/api/teachers/${id}/dashboard`,p),api.get(`/api/teachers/${id}/classes`,p),api.get(`/api/teachers/${id}/students`,p),api.get(`/api/teachers/${id}/timetable`,p),api.get(`/api/teachers/${id}/assignments`,p),api.get(`/api/teachers/${id}/workload`,p)]);setDash(d.data);setClasses(unwrap(c.data));setStudents(unwrap(s.data));setTimetable(unwrap(t.data));setAssignments(unwrap(a.data));setWorkload(w.data);}catch(e){notify({kind:"error",title:"Teacher workspace unavailable",message:getErrorMessage(e)})}finally{end();}}
 useEffect(()=>{void load()},[]);
 const id=me?.employeeId??me?.EmployeeId;
 async function createAssignment(){if(!id||!assignment.Title||!assignment.CourseOfferingId){notify({kind:"error",title:"Required fields",message:"Title and course offering are required."});return;}const end=beginBusy("Publishing assignment…");try{await api.post(`/api/teachers/${id}/assignments`,{...assignment,TenantId:tenant,ClassSectionId:assignment.ClassSectionId||null,DueAt:assignment.DueAt||null});setAssignmentOpen(false);notify({kind:"success",title:"Assignment published",message:"Students can now see the assignment."});await load();}catch(e){notify({kind:"error",title:"Could not create assignment",message:getErrorMessage(e)})}finally{end();}}
 async function applyLeave(){if(!id||!leave.FromDate||!leave.ToDate||!leave.Reason){notify({kind:"error",title:"Required fields",message:"Dates and reason are required."});return;}const end=beginBusy("Submitting leave request…");try{await api.post(`/api/teachers/${id}/leave`,{...leave,TenantId:tenant});setLeaveOpen(false);notify({kind:"success",title:"Leave submitted",message:"Your request is pending approval."});}catch(e){notify({kind:"error",title:"Could not submit leave",message:getErrorMessage(e)})}finally{end();}}
 const metrics=useMemo(()=>[{label:"Students",value:val(dash,"students"),icon:Users},{label:"Course assignments",value:val(dash,"activeCourseAssignments"),icon:BookOpen},{label:"Assignments",value:val(dash,"assignments"),icon:ClipboardCheck},{label:"To grade",value:val(dash,"submissionsToGrade"),icon:Gauge}], [dash]);
 return <><PageHeader title={`Teacher Workspace${me?` · ${val(me,"firstName")} ${val(me,"lastName")}`:""}`} subtitle="Classes, students, timetable, assignments, grading, workload and leave — connected to the teacher backend" action={<div className="page-actions"><button className="secondary" onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button><button className="secondary" onClick={()=>setLeaveOpen(true)}>Request leave</button><button className="primary" onClick={()=>setAssignmentOpen(true)}><Plus size={15}/> Assignment</button></div>}/>
 <section className="metric-grid role-metrics">{metrics.map(x=><article className="metric-card" key={x.label}><span className="metric-icon"><x.icon size={17}/></span><div className="metric-label">{x.label}</div><div className="metric-value">{String(x.value)}</div></article>)}</section>
 <div className="module-tabs">{["overview","classes","students","timetable","assignments","workload"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 {tab==="overview"&&<div className="dashboard-two"><section className="surface dashboard-card"><div className="surface-head"><div><h3>Today's timetable</h3><p>Your live teaching schedule</p></div><CalendarDays size={18}/></div><div className="timeline-list">{timetable.slice(0,6).map((r,i)=><div key={i}><b>{String(val(r,"startTime"))}</b><span>{String(val(r,"period"))}</span><small>Day {String(val(r,"dayOfWeek"))} · Section {String(val(r,"classSectionId"))}</small></div>)}{!timetable.length&&<div className="empty-state">No timetable entries.</div>}</div></section><section className="surface dashboard-card"><div className="surface-head"><div><h3>Workload</h3><p>Current teaching allocation</p></div></div><div className="mini-stat-row"><div><b>{String(val(workload,"periodsPerWeek"))}</b><span>Periods / week</span></div><div><b>{String(val(workload,"classes"))}</b><span>Classes</span></div><div><b>{String(val(workload,"activeAssignments"))}</b><span>Active allocations</span></div></div></section></div>}
 {tab!=="overview"&&<DataTable rows={tab==="classes"?classes:tab==="students"?students:tab==="timetable"?timetable:tab==="assignments"?assignments:[workload]} title={tab}/>} 
 <Modal open={assignmentOpen} title="Create assignment" onClose={()=>setAssignmentOpen(false)}><div className="human-form-grid"><Field label="Title" value={assignment.Title} onChange={v=>setAssignment({...assignment,Title:v})}/><Field label="Type" value={assignment.Type} onChange={v=>setAssignment({...assignment,Type:v})}/><Field label="Course offering ID" value={assignment.CourseOfferingId} onChange={v=>setAssignment({...assignment,CourseOfferingId:v})}/><Field label="Class section ID" value={assignment.ClassSectionId} onChange={v=>setAssignment({...assignment,ClassSectionId:v})}/><Field label="Due at" type="datetime-local" value={assignment.DueAt} onChange={v=>setAssignment({...assignment,DueAt:v})}/><Field label="Total marks" type="number" value={assignment.TotalMarks} onChange={v=>setAssignment({...assignment,TotalMarks:Number(v)})}/><label className="human-field field-wide"><span>Description</span><textarea value={assignment.Description} onChange={e=>setAssignment({...assignment,Description:e.target.value})}/></label><label className="human-field field-wide"><span>Instructions</span><textarea value={assignment.Instructions} onChange={e=>setAssignment({...assignment,Instructions:e.target.value})}/></label></div><div className="modal-actions"><button className="secondary" onClick={()=>setAssignmentOpen(false)}>Cancel</button><button className="primary" onClick={()=>void createAssignment()}>Publish assignment</button></div></Modal>
 <Modal open={leaveOpen} title="Request leave" onClose={()=>setLeaveOpen(false)}><div className="human-form-grid"><Field label="From" type="date" value={leave.FromDate} onChange={v=>setLeave({...leave,FromDate:v})}/><Field label="To" type="date" value={leave.ToDate} onChange={v=>setLeave({...leave,ToDate:v})}/><Field label="Leave type" value={leave.LeaveType} onChange={v=>setLeave({...leave,LeaveType:v})}/><label className="human-field field-wide"><span>Reason</span><textarea value={leave.Reason} onChange={e=>setLeave({...leave,Reason:e.target.value})}/></label></div><div className="modal-actions"><button className="secondary" onClick={()=>setLeaveOpen(false)}>Cancel</button><button className="primary" onClick={()=>void applyLeave()}>Submit request</button></div></Modal></>;
}
function Field({label,value,onChange,type="text"}:{label:string,value:any,onChange:(v:string)=>void,type?:string}){return <label className="human-field"><span>{label}</span><input type={type} value={value??""} onChange={e=>onChange(e.target.value)}/></label>}
function DataTable({rows,title}:{rows:Row[],title:string}){const cols=rows[0]?Object.keys(rows[0]).slice(0,8):[];return <section className="surface data-surface"><div className="surface-head"><div><h3>{title[0].toUpperCase()+title.slice(1)}</h3><p>{rows.length} live records</p></div></div><div className="table-wrap"><table className="premium-table"><thead><tr>{cols.map(c=><th key={c}>{c.replace(/([A-Z])/g," $1")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{typeof r[c]==="object"?JSON.stringify(r[c]):String(r[c]??"—")}</td>)}</tr>)}{!rows.length&&<tr><td><div className="empty-state">No records available.</div></td></tr>}</tbody></table></div></section>}
export function TeachersPage(){const {user}=useAuth();return user?.roles.includes("Teacher") ? <TeacherWorkspace /> : <HrPage />}
