import{createBrowserRouter}from'react-router-dom';
import{AppShell}from'../../components/layout/AppShell';
import{DashboardPage}from'../../features/dashboard/pages/DashboardPage';
import{StudentsPage}from'../../features/students/pages/StudentsPage';
import{TeachersPage}from'../../features/teachers/pages/TeachersPage';
import{AcademicsPage}from'../../features/academics/pages/AcademicsPage';
import{ExaminationsPage}from'../../features/examinations/pages/ExaminationsPage';
import{AttendancePage}from'../../features/attendance/pages/AttendancePage';
import{FinancePage}from'../../features/finance/pages/FinancePage';
import{HrPage}from'../../features/hr/pages/HrPage';
import{LibraryPage}from'../../features/library/pages/LibraryPage';
import{TransportPage}from'../../features/transport/pages/TransportPage';
import{CommunicationPage}from'../../features/communication/pages/CommunicationPage';
import{AiPage}from'../../features/ai/pages/AiPage';
import{ReportsPage}from'../../features/reports/pages/ReportsPage';
import{SettingsPage}from'../../features/settings/pages/SettingsPage';
export const router=createBrowserRouter([{path:'/',element:<AppShell/>,children:[{index:true,element:<DashboardPage/>},{path:'students',element:<StudentsPage/>},{path:'teachers',element:<TeachersPage/>},{path:'academics',element:<AcademicsPage/>},{path:'examinations',element:<ExaminationsPage/>},{path:'attendance',element:<AttendancePage/>},{path:'finance',element:<FinancePage/>},{path:'hr',element:<HrPage/>},{path:'library',element:<LibraryPage/>},{path:'transport',element:<TransportPage/>},{path:'communication',element:<CommunicationPage/>},{path:'ai',element:<AiPage/>},{path:'reports',element:<ReportsPage/>},{path:'settings',element:<SettingsPage/>}]}]);