import { NavLink } from "react-router-dom";
import { Activity, BarChart3, Bell, BookOpen, Bot, BriefcaseBusiness, Bus, CalendarCheck, ClipboardCheck, GraduationCap, HeartPulse, LayoutDashboard, ListTree, MessageCircle, Settings, ShieldCheck, SlidersHorizontal, Users, Wallet, Workflow, X } from "lucide-react";
import { useAuth } from "../../features/auth/auth";
type NavItem=[string,string,any,string[]];
const navigation:NavItem[]=[
 ["/","Dashboard",LayoutDashboard,["*"]],
 ["/tenancy","Tenants",GraduationCap,["SuperAdmin"]],["/platform","Tenant Users",Users,["SuperAdmin"]],["/platform/features","Plans & Features",SlidersHorizontal,["SuperAdmin"]],["/audit","Audit & Impersonation",ShieldCheck,["SuperAdmin"]],["/observability","API Health & Error Logs",HeartPulse,["SuperAdmin"]],
 ["/organization","Branches",GraduationCap,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal"]],["/students","Students",Users,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal","Teacher"]],["/teachers","Teachers & Staff",Users,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal"]],["/academics","Classes, Courses & Timetable",BookOpen,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal","Teacher","Student","Parent"]],["/attendance","Attendance",CalendarCheck,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal","Teacher","Student","Parent"]],["/examinations","Assignments, Tests & Results",ClipboardCheck,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal","Teacher","Student","Parent","Examiner"]],["/finance","Fees & Finance",Wallet,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Accountant","Parent","Student"]],["/hr","HR, Payroll & Leave",BriefcaseBusiness,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal","HRManager","Staff","Teacher"]],["/transport","Transport",Bus,["SchoolAdmin","TenantAdmin","Admin","AdminOffice","TransportManager","Driver","Parent"]],["/workflow","Approvals",Workflow,["SuperAdmin","SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal","Teacher","Parent"]],
 ["/ai","Predictions & AI",Bot,["*"]],["/communication","Chat",MessageCircle,["*"]],["/notifications","Notifications",Bell,["*"]],["/reports","Reports & Analytics",BarChart3,["SuperAdmin","SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal","Examiner"]],["/reference","Lookups",ListTree,["SuperAdmin","SchoolAdmin","TenantAdmin","Admin","AdminOffice"]],["/settings","Settings",Settings,["SuperAdmin","SchoolAdmin","TenantAdmin","Admin","AdminOffice","Principal"]]
];
export function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){const{user}=useAuth();const roles=user?.roles?.length?user.roles:[user?.role||""];const isSuper=roles.includes("SuperAdmin");const visible=navigation.filter(([, , ,a])=>a.includes("*")||a.some(r=>roles.includes(r)));return <>{open&&<button className="sidebar-backdrop" aria-label="Close navigation" onClick={onClose}/>}<aside className={`sidebar ${open?"open":""}`}><div className="sidebar-head"><div className="brand"><span className="brand-mark"><GraduationCap size={22}/></span><span>Smart<b>School</b></span></div><button className="sidebar-close" onClick={onClose}><X size={20}/></button></div><div className="school-chip"><span>{user?.initials||"SS"}</span><div><b>{user?.name||"SmartSchool"}</b><small>{isSuper?"Platform master workspace":`${user?.role||"User"} workspace`}</small></div></div><div className="nav-label">{isSuper?"Platform administration":"Workspace"}</div><nav className="nav">{visible.map(([to,label,Icon])=><NavLink key={`${to}-${label}`} to={to} end={to==="/"} onClick={onClose}><Icon size={18}/><span>{label}</span></NavLink>)}</nav>{isSuper&&<div className="sidebar-upgrade"><Activity size={20}/><b>Platform services</b><span>PostgreSQL • Redis • Kafka • AI</span><div className="health-line"><i/> Observability enabled</div></div>}</aside></>}
