import { createContext, type ReactNode, useContext, useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, Info, LoaderCircle, TriangleAlert, X } from "lucide-react";
export type ToastKind="success"|"error"|"warning"|"info";
export type ToastInput=string|{title?:string;message:string;kind?:ToastKind;duration?:number};
type Toast={id:number;title:string;message:string;kind:ToastKind};
type ConfirmOptions={title:string;message:string;confirmText?:string;danger?:boolean};
type ConfirmState=ConfirmOptions&{resolve:(value:boolean)=>void};
type UiValue={notify:(input:ToastInput)=>void;beginBusy:(label?:string)=>()=>void;confirm:(options:ConfirmOptions)=>Promise<boolean>};
const UiContext=createContext<UiValue|undefined>(undefined);
export function UiProvider({children}:{children:ReactNode}){const[toasts,setToasts]=useState<Toast[]>([]);const[busy,setBusy]=useState<string[]>([]);const[confirmation,setConfirmation]=useState<ConfirmState|null>(null);const seq=useRef(1);const value=useMemo<UiValue>(()=>({notify:(input)=>{const x=typeof input==="string"?{message:input}:input;const kind=x.kind??"success";const id=seq.current++;const title=x.title??({success:"Success",error:"Something went wrong",warning:"Attention",info:"Information"} as const)[kind];setToasts(v=>[...v.slice(-3),{id,title,message:x.message,kind}]);window.setTimeout(()=>setToasts(v=>v.filter(t=>t.id!==id)),x.duration??4200)},beginBusy:(label="Working…")=>{const token=`${Date.now()}-${Math.random()}`;setBusy(v=>[...v,`${token}|${label}`]);return()=>setBusy(v=>v.filter(x=>!x.startsWith(`${token}|`)))},confirm:(options)=>new Promise<boolean>(resolve=>setConfirmation({...options,resolve}))}),[]);const icon=(k:ToastKind)=>k==="success"?<CheckCircle2 size={20}/>:k==="error"?<AlertCircle size={20}/>:k==="warning"?<TriangleAlert size={20}/>:<Info size={20}/>;const finish=(answer:boolean)=>{confirmation?.resolve(answer);setConfirmation(null)};return <UiContext.Provider value={value}>{children}{busy.length>0&&<div className="global-loader" role="status"><div><LoaderCircle className="spin" size={24}/><b>{busy.at(-1)?.split("|").slice(1).join("|")||"Working…"}</b><span>Please wait while SmartSchool completes the request.</span></div></div>}<div className="toast-stack" aria-live="polite">{toasts.map(t=><div className={`toast toast-${t.kind}`} key={t.id}><span className="toast-icon">{icon(t.kind)}</span><div className="toast-copy"><b>{t.title}</b><span>{t.message}</span></div><button aria-label="Dismiss" onClick={()=>setToasts(v=>v.filter(x=>x.id!==t.id))}><X size={16}/></button></div>)}</div>{confirmation&&<Modal open title={confirmation.title} onClose={()=>finish(false)}><div className="confirm-copy"><TriangleAlert size={28}/><p>{confirmation.message}</p></div><div className="modal-actions"><button className="secondary" onClick={()=>finish(false)}>Cancel</button><button className={confirmation.danger?"danger-button":"primary"} onClick={()=>finish(true)}>{confirmation.confirmText??"Confirm"}</button></div></Modal>}</UiContext.Provider>}
export function useUi(){const v=useContext(UiContext);if(!v)throw new Error("UiProvider required");return v}
export function Modal({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){if(!open)return null;return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal-card" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><header className="modal-head"><div><span className="eyebrow">SmartSchool</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={19}/></button></header>{children}</section></div>}
