import{useEffect,useMemo,useState}from"react";import axios from"axios";import{Plus,RefreshCw,Search,Trash2,Pencil}from"lucide-react";import{env}from"../../config/env";import{http}from"../../core/api/httpClient";import{Modal,useUi}from"./InteractiveUi";import{PageHeader}from"./PageHeader";
type Row=Record<string,any>;type Spec={paths:Record<string,Record<string,any>>};const pretty=(s:string)=>s.replaceAll("-"," ").replace(/\b\w/g,x=>x.toUpperCase());const unwrap=(d:any)=>{const x=d?.value??d;return x?.items??x?.Items??(Array.isArray(x)?x:[])};const show=(v:any)=>v==null?"—":typeof v==="object"?JSON.stringify(v):String(v);
export function RealModulePage({module}:{module:string}){const{notify}=useUi();const[spec,setSpec]=useState<Spec|null>(null),[resource,setResource]=useState(""),[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(""),[selected,setSelected]=useState<Row|null>(null),[edit,setEdit]=useState(false),[draft,setDraft]=useState("{}"),[loading,setLoading]=useState(false);
useEffect(()=>{axios.get(`${env.apiBaseUrl}/openapi/v1.json`).then(r=>setSpec(r.data)).catch(()=>notify("Cannot load SmartSchool OpenAPI."))},[]);
const resources=useMemo(()=>{if(!spec)return[];const pre=`/api/${module}/`;return Object.keys(spec.paths).filter(p=>p.startsWith(pre)&&!p.includes("{")).map(p=>p.slice(pre.length)).filter((x,i,a)=>x&&a.indexOf(x)===i).sort()},[spec,module]);useEffect(()=>{if(resources.length&&!resources.includes(resource))setResource(resources[0])},[resources]);
const base=resource?`/api/${module}/${resource}`:"";const tenant=()=>sessionStorage.getItem("tenant_id")||env.tenantId;
async function load(){if(!base)return;setLoading(true);try{const{data}=await http.get(base,{params:{tenantId:tenant(),page:1,pageSize:100}});setRows(unwrap(data))}catch(e:any){notify(e.response?.data?.detail||`Failed to load ${resource}`)}finally{setLoading(false)}}useEffect(()=>{void load()},[base]);
const filtered=useMemo(()=>rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[rows,q]);const cols=useMemo(()=>rows[0]?Object.keys(rows[0]).filter(x=>!["photo","rowVersion","content"].includes(x)).slice(0,7):[],[rows]);
function create(){setSelected(null);setDraft(JSON.stringify({tenantId:tenant()},null,2));setEdit(true)}function modify(r:Row){setSelected(r);setDraft(JSON.stringify(r,null,2));setEdit(true)}
async function save(){try{const body=JSON.parse(draft);selected?.id?await http.put(`${base}/${selected.id}`,body):await http.post(base,body);notify("Saved to database.");setEdit(false);setSelected(null);await load()}catch(e:any){notify(e.response?.data?.detail||e.response?.data?.title||e.message)}}
async function del(r:Row){if(!r.id||!confirm("Delete record?"))return;try{await http.delete(`${base}/${r.id}`,{params:{tenantId:tenant()}});notify("Deleted.");setSelected(null);await load()}catch(e:any){notify(e.response?.data?.detail||"Delete failed")}}
return <><PageHeader title={pretty(module)} subtitle="Live database-backed SmartSchool API" action={<button className="primary" onClick={create}><Plus size={16}/>Add {pretty(resource||"record")}</button>}/><section className="surface data-surface"><div className="surface-head"><div><h3>API resources</h3><p>{resources.length} resources discovered from backend contract</p></div><button className="icon-button" onClick={load}><RefreshCw size={16}/></button></div><div className="data-toolbar"><select className="filter-select" value={resource} onChange={e=>setResource(e.target.value)}>{resources.map(x=><option key={x}>{x}</option>)}</select><label className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search live data"/></label></div><div className="table-wrap"><table className="premium-table"><thead><tr>{cols.map(c=><th key={c}>{pretty(c)}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id||i} onClick={()=>setSelected(r)}>{cols.map(c=><td key={c}>{show(r[c])}</td>)}<td><button className="icon-button" onClick={e=>{e.stopPropagation();modify(r)}}><Pencil size={14}/></button><button className="icon-button" onClick={e=>{e.stopPropagation();void del(r)}}><Trash2 size={14}/></button></td></tr>)}{!filtered.length&&<tr><td colSpan={cols.length+1}><div className="empty-state">{loading?"Loading…":"No records."}</div></td></tr>}</tbody></table></div><div className="table-footer">{filtered.length} live records</div></section>
<Modal open={!!selected&&!edit} title={pretty(resource)} onClose={()=>setSelected(null)}>{selected&&<div className="detail-grid">{Object.entries(selected).map(([k,v])=><div key={k}><span>{pretty(k)}</span><b>{show(v)}</b></div>)}</div>}</Modal>
<Modal open={edit} title={`${selected?"Edit":"Create"} ${pretty(resource)}`} onClose={()=>setEdit(false)}><p className="muted">Live request body. Fields match the backend DTO names.</p><textarea className="form-control" style={{minHeight:360,fontFamily:"monospace"}} value={draft} onChange={e=>setDraft(e.target.value)}/><div className="modal-actions"><button className="secondary" onClick={()=>setEdit(false)}>Cancel</button><button className="primary" onClick={()=>void save()}>Save</button></div></Modal></>}
